/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vulkan.gui;

import javax.imageio.ImageIO;

/**
 *
 * @author gabri
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        Card = new javax.swing.JPanel();
        Grid_1_1 = new javax.swing.JPanel();
        img_inicio = new javax.swing.JLabel();
        Grid_1_2 = new javax.swing.JPanel();
        login_box = new javax.swing.JPanel();
        lbl_ingresar_datos = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        lbl_contrasenia = new javax.swing.JLabel();
        btn_iniciar_sesion = new javax.swing.JButton();
        img_usuario = new javax.swing.JLabel();
        img_contrasenia = new javax.swing.JLabel();
        txt_contrasenia = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setEnabled(false);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        Background.setBackground(new java.awt.Color(244, 255, 255));
        Background.setPreferredSize(new java.awt.Dimension(1280, 720));
        Background.setLayout(new java.awt.CardLayout(300, 175));

        Card.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Card.setLayout(new java.awt.GridLayout(1, 2));

        Grid_1_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img_inicio.setIcon(new javax.swing.ImageIcon("/home/fer3dev/NetBeansProjects/vulkan/src/main/java/com/mycompany/vulkan/Imagenes/incio.jpg")); // NOI18N
        Grid_1_1.add(img_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 370));

        Card.add(Grid_1_1);

        Grid_1_2.setBackground(new java.awt.Color(255, 255, 255));
        Grid_1_2.setLayout(new java.awt.GridBagLayout());

        login_box.setBackground(new java.awt.Color(255, 255, 255));
        login_box.setPreferredSize(new java.awt.Dimension(300, 300));

        lbl_ingresar_datos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbl_ingresar_datos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_ingresar_datos.setText("INGRESE SUS DATOS");

        lbl_usuario.setText("Usuario");

        txt_usuario.setToolTipText("");

        lbl_contrasenia.setText("Contraseña");

        btn_iniciar_sesion.setText("Inicia Sesión");
        btn_iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciar_sesionActionPerformed(evt);
            }
        });

        img_usuario.setIcon(new javax.swing.ImageIcon("/home/fer3dev/NetBeansProjects/vulkan/src/main/java/com/mycompany/vulkan/Imagenes/user.png")); // NOI18N

        img_contrasenia.setIcon(new javax.swing.ImageIcon("/home/fer3dev/NetBeansProjects/vulkan/src/main/java/com/mycompany/vulkan/Imagenes/pass.png")); // NOI18N

        txt_contrasenia.setToolTipText("");

        javax.swing.GroupLayout login_boxLayout = new javax.swing.GroupLayout(login_box);
        login_box.setLayout(login_boxLayout);
        login_boxLayout.setHorizontalGroup(
            login_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_boxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_iniciar_sesion)
                .addGap(81, 81, 81))
            .addGroup(login_boxLayout.createSequentialGroup()
                .addGroup(login_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(login_boxLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_ingresar_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, login_boxLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(login_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_usuario)
                            .addGroup(login_boxLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(login_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(login_boxLayout.createSequentialGroup()
                                        .addGroup(login_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(login_boxLayout.createSequentialGroup()
                                                .addComponent(img_contrasenia)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbl_contrasenia))
                                            .addGroup(login_boxLayout.createSequentialGroup()
                                                .addComponent(img_usuario)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lbl_usuario)))
                                        .addGap(128, 128, 128))
                                    .addComponent(txt_contrasenia))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        login_boxLayout.setVerticalGroup(
            login_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_boxLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_ingresar_datos)
                .addGap(24, 24, 24)
                .addGroup(login_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(login_boxLayout.createSequentialGroup()
                        .addComponent(lbl_usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(login_boxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(img_contrasenia)
                            .addComponent(lbl_contrasenia)))
                    .addComponent(img_usuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_contrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btn_iniciar_sesion)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        Grid_1_2.add(login_box, new java.awt.GridBagConstraints());

        Card.add(Grid_1_2);

        Background.add(Card, "card2");

        getContentPane().add(Background, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciar_sesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_iniciar_sesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Card;
    private javax.swing.JPanel Grid_1_1;
    private javax.swing.JPanel Grid_1_2;
    private javax.swing.JButton btn_iniciar_sesion;
    private javax.swing.JLabel img_contrasenia;
    private javax.swing.JLabel img_inicio;
    private javax.swing.JLabel img_usuario;
    private javax.swing.JLabel lbl_contrasenia;
    private javax.swing.JLabel lbl_ingresar_datos;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPanel login_box;
    private javax.swing.JPasswordField txt_contrasenia;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
