/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vulkan.gui;
import com.mycompany.controlador.controlEmpleado;
import com.mycompany.vulkan.validacion.valEmail;
import com.mycompany.vulkan.validacion.valNumero;
import com.mycompany.vulkan.validacion.valString;
import javax.swing.table.DefaultTableModel;
import vulkan.declaracion.decEmpleado;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import vulkan.declaracion.decPuesto;
import com.mycompany.controlador.controlPuesto;
import com.mycompany.controlador.controlTipoDeDocumento;
import static com.mycompany.vulkan.gui.jFrameClientes.ValidacionDNI;
import static com.mycompany.vulkan.gui.jFrameClientes.ValidacionRTN;
import static com.mycompany.vulkan.gui.jFrameClientes.Validacionvisa;
import static java.lang.Integer.parseInt;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.ImageIcon;
import javax.swing.table.TableModel;
import vulkan.declaracion.decClientes;
import vulkan.declaracion.decTipoDeDocumento;
/**
 *
 * @author gabri
 */
public class jFrameEmpleado extends javax.swing.JFrame {
    valString valS = new valString();
    valNumero valN = new valNumero();
    controlEmpleado empleadoDao = new controlEmpleado();
    decEmpleado empleado = new decEmpleado();
    controlPuesto puestoDao = new controlPuesto();
    decPuesto puesto = new decPuesto();
    controlTipoDeDocumento tipoDocumentoDao = new controlTipoDeDocumento();
    /**
     * Creates new form jFrameEmpleado
     */
    public jFrameEmpleado() {
        initComponents();
        ImageIcon icon = new ImageIcon(getClass().getResource("/Imagenes/logo1.png"));
        setIconImage(icon.getImage());
        setTitle("VK Restaurant");
        this.llenadoTabla();
        this.comboBoxPuesto();
        this.comboBoxTipoDoc();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lbl_menu_restaurante = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        lbl_id_menu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_direccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_telefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbb_puesto = new javax.swing.JComboBox<>();
        cbb_documento = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txt_id_area = new javax.swing.JTextField();
        txt_id_documento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_nombre_tipoDocumento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_registros = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_desactivar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(244, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1280, 300));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setPreferredSize(new java.awt.Dimension(1280, 50));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        lbl_menu_restaurante.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_menu_restaurante.setText("Empleado");
        jPanel5.add(lbl_menu_restaurante, new java.awt.GridBagConstraints());

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel6.setBackground(new java.awt.Color(244, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_id_menu.setText("ID");
        jPanel7.add(lbl_id_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel1.setText("Nombre");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel5.setText("Apellido");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel6.setText("Dirección");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel7.setText("Email");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_emailKeyTyped(evt);
            }
        });
        jPanel7.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 200, -1));

        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nombreKeyTyped(evt);
            }
        });
        jPanel7.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 200, -1));

        txt_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_apellidoKeyTyped(evt);
            }
        });
        jPanel7.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 200, -1));

        txt_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_direccionKeyTyped(evt);
            }
        });
        jPanel7.add(txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, -1));

        jLabel4.setText("Teléfono");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, -1));

        txt_telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefonoKeyTyped(evt);
            }
        });
        jPanel7.add(txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 150, -1));

        jLabel8.setText("Puesto");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        cbb_puesto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_puestoItemStateChanged(evt);
            }
        });
        jPanel7.add(cbb_puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 150, -1));

        cbb_documento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_documentoItemStateChanged(evt);
            }
        });
        jPanel7.add(cbb_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 150, -1));

        jLabel9.setText("Tipo de documento");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        txt_id_area.setEditable(false);
        txt_id_area.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.add(txt_id_area, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, -1));

        txt_id_documento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_id_documentoKeyTyped(evt);
            }
        });
        jPanel7.add(txt_id_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 150, -1));

        jLabel10.setText("Numero Identidad");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        txt_nombre_tipoDocumento.setEditable(false);
        txt_nombre_tipoDocumento.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.add(txt_nombre_tipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 150, -1));

        jLabel12.setText("Nombre del documento");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        btn_limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/limpiar50.png"))); // NOI18N
        btn_limpiar.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        jPanel7.add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, -1, -1));

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 810, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BackgroundRes.png"))); // NOI18N
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(244, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_registros.setGridColor(new java.awt.Color(0, 0, 0));
        tbl_registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_registrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_registros);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1280, 310));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar1.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        btn_agregar.setBackground(new java.awt.Color(204, 204, 204));
        btn_agregar.setForeground(new java.awt.Color(0, 0, 255));
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Añadir1.png"))); // NOI18N
        btn_agregar.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        btn_modificar.setBackground(new java.awt.Color(204, 204, 204));
        btn_modificar.setForeground(new java.awt.Color(0, 0, 255));
        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar1.png"))); // NOI18N
        btn_modificar.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, -1, -1));

        btn_desactivar.setBackground(new java.awt.Color(204, 204, 204));
        btn_desactivar.setForeground(new java.awt.Color(0, 0, 255));
        btn_desactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Desactivar1.png"))); // NOI18N
        btn_desactivar.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_desactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desactivarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_desactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, -1, -1));

        btn_regresar.setBackground(new java.awt.Color(204, 204, 204));
        btn_regresar.setForeground(new java.awt.Color(255, 0, 51));
        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar1.png"))); // NOI18N
        btn_regresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        btn_regresar.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 50, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BackgroundRes.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -250, -1, -1));

        jPanel3.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void llenadoTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        tbl_registros.setModel(modelo);
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Telefono");
        modelo.addColumn("Direccion");
        modelo.addColumn("Email");
        modelo.addColumn("Puesto");
        modelo.addColumn("ID tipo documento");
        modelo.addColumn("Nombre del tipo de documento");
        modelo.addColumn("Numero de identidad empleado");
        List<decEmpleado> puesto = empleadoDao.findclientesEntities();

        for(decEmpleado cliente : puesto){
            modelo.addRow(
                new Object[]{

                    cliente.getId_empleado(),
                    cliente.getNombre(),
                    cliente.getApellido(),
                    cliente.getTelefono(),
                    cliente.getDireccion(),
                    cliente.getEmail(),

                    cliente.getEmpleadoNombre_puesto(),
                    cliente.getId_tipo_documento(),
                    cliente.getNombre_documento(),
                    cliente.getNumIdentida_empleado(),
                }
            );
        }
        btn_modificar.setEnabled(false);
        btn_desactivar.setEnabled(false);
        btn_agregar.setEnabled(true);
        
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.llenadoTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        boolean email= false;
        int a= 0;
        if(valString.tresKey(txt_email.getText())== false){
            
        }else{
            email = valEmail.email(txt_email.getText());
        }
        if(valNumero.unoKey(txt_telefono.getText())== false){
            
        }else{
            a = Integer.parseInt(txt_telefono.getText());
        }
        
        
        int b = Integer.parseInt(Integer.toString(a).substring(0, 1));
       

        if(valString.tresKey(txt_nombre.getText())== false){  
            JOptionPane.showMessageDialog(this, "Error nombre tiene menos de 3 letras");
        }else if(valString.tresLetrasRepetidas(txt_nombre.getText()) == false){
            JOptionPane.showMessageDialog(this, "Error nombre tiene 3 letras repetidas");
        }else if(valString.tresKey(txt_direccion.getText())== false){
            JOptionPane.showMessageDialog(this, "Error en dirección tiene menos de 3 caracteres");
        }else if(email == false){
            JOptionPane.showMessageDialog(this, "email No valido");
        }else if(valString.tresKey(txt_apellido.getText())== false){
            JOptionPane.showMessageDialog(this, "Error en apellido tiene menos de 3 caracteres");
        }else if(valNumero.telefono(b)== false){
            JOptionPane.showMessageDialog(this, "Error numero no posee en su prinicipio a 2 7 8 9");
        }else if(valNumero.telefonoOcho(txt_telefono.getText()) ==false){
            JOptionPane.showMessageDialog(this, "Error teléfono no posee 8 numeros");
        }else if(String.valueOf(cbb_puesto.getSelectedItem()) == "Seleccionar"){
            JOptionPane.showMessageDialog(this, "Error puesto no esta seleccionado");
        }else if(String.valueOf(cbb_documento.getSelectedItem()) == "Seleccionar"){
            JOptionPane.showMessageDialog(this, "Error documento no esta seleccionado");
        }else if(String.valueOf(cbb_documento.getSelectedItem()) == "DNI"){
            JOptionPane.showMessageDialog(this, "Slecione el dni");
        }else if( (String.valueOf(txt_nombre_tipoDocumento.getText()).equalsIgnoreCase("DNI") 
                && ValidacionDNI(txt_id_documento.getText()) == false ) 
                || (String.valueOf(cbb_documento.getSelectedItem()).equalsIgnoreCase("identidad") 
                && ValidacionDNI(txt_id_documento.getText()) == false ) 
                || (String.valueOf(txt_nombre_tipoDocumento.getText()).equalsIgnoreCase("RTN") 
                && ValidacionRTN(txt_id_documento.getText())== false)
                || String.valueOf(cbb_documento.getSelectedItem()).equalsIgnoreCase("VISA")
                && Validacionvisa(txt_id_documento.getText())){
                
            JOptionPane.showMessageDialog(this, "Error Formato de identidad no aceptado");      
        }
        else{
            JOptionPane.showMessageDialog(this, "Guardando");
            
            empleado.setNombre(txt_nombre.getText());
            empleado.setApellido(txt_apellido.getText());
            empleado.setTelefono(Integer.parseInt(txt_telefono.getText()));
            empleado.setEmail(txt_email.getText());
            empleado.setDireccion(txt_direccion.getText());
            
            empleado.setNumIdentida_empleado(txt_id_documento.getText());
            empleado.setNombre_documento(txt_nombre_tipoDocumento.getText());
            empleado.setId_tipo_documento(parseInt(cbb_documento.getSelectedItem().toString()));
            
            empleado.setEmpleadoNombre_puesto(cbb_puesto.getSelectedItem().toString());
            llenadoTabla();
        try {
            empleadoDao.guardar(empleado);
        } catch (Exception ex) {
            Logger.getLogger(jFrameEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
        boolean email= false;
        int a= 0;
        if(valString.tresKey(txt_email.getText())== false){
            
        }else{
            email = valEmail.email(txt_email.getText());
        }
        if(valNumero.unoKey(txt_telefono.getText())== false){
            
        }else{
            a = Integer.parseInt(txt_telefono.getText());
        }
        
        
        int b = Integer.parseInt(Integer.toString(a).substring(0, 1));
       

        if(valString.tresKey(txt_nombre.getText())== false){  
            JOptionPane.showMessageDialog(this, "Error nombre tiene menos de 3 letras");
        }else if(valString.tresLetrasRepetidas(txt_nombre.getText()) == false){
            JOptionPane.showMessageDialog(this, "Error nombre tiene 3 letras repetidas");
        }else if(valString.tresKey(txt_direccion.getText())== false){
            JOptionPane.showMessageDialog(this, "Error en dirección tiene menos de 3 caracteres");
        }else if(email == false){
            JOptionPane.showMessageDialog(this, "email No valido");
        }else if(valString.tresKey(txt_apellido.getText())== false){
            JOptionPane.showMessageDialog(this, "Error en apellido tiene menos de 3 caracteres");
        }else if(valNumero.telefono(b)== false){
            JOptionPane.showMessageDialog(this, "Error numero no posee en su prinicipio a 2 7 8 9");
        }else if(valNumero.telefonoOcho(txt_telefono.getText()) ==false){
            JOptionPane.showMessageDialog(this, "Error teléfono no posee 8 numeros");
        }else if(String.valueOf(cbb_puesto.getSelectedItem()) == "Seleccionar"){
            JOptionPane.showMessageDialog(this, "Error puesto no esta seleccionado");
        }else if(String.valueOf(cbb_documento.getSelectedItem()) == "Seleccionar"){
            JOptionPane.showMessageDialog(this, "Error documento no esta seleccionado");
        }else if(String.valueOf(cbb_documento.getSelectedItem()) == "DNI"){
            JOptionPane.showMessageDialog(this, "Slecione el dni");
        }else if( (String.valueOf(txt_nombre_tipoDocumento.getText()).equalsIgnoreCase("DNI") 
                && ValidacionDNI(txt_id_documento.getText()) == false ) 
                || (String.valueOf(cbb_documento.getSelectedItem()).equalsIgnoreCase("identidad") 
                && ValidacionDNI(txt_id_documento.getText()) == false ) 
                || (String.valueOf(txt_nombre_tipoDocumento.getText()).equalsIgnoreCase("RTN") 
                && ValidacionRTN(txt_id_documento.getText())== false)
                || String.valueOf(cbb_documento.getSelectedItem()).equalsIgnoreCase("VISA")
                && Validacionvisa(txt_id_documento.getText())){
                
            JOptionPane.showMessageDialog(this, "Error Formato de identidad no aceptado");      
        }
        else{
            JOptionPane.showMessageDialog(this, "Guardando");
            
            empleado.setNombre(txt_nombre.getText());
            empleado.setApellido(txt_apellido.getText());
            empleado.setTelefono(Integer.parseInt(txt_telefono.getText()));
            empleado.setEmail(txt_email.getText());
            empleado.setDireccion(txt_direccion.getText());
            
            empleado.setNumIdentida_empleado(txt_id_documento.getText());
            empleado.setEmpleadoNombre_puesto(cbb_puesto.getSelectedItem().toString());
            empleado.setNombre_documento(txt_nombre_tipoDocumento.getText());
            empleado.setId_tipo_documento(parseInt(cbb_documento.getSelectedItem().toString()));
            llenadoTabla();
        try {
            empleadoDao.edit(empleado);
        } catch (Exception ex) {
            Logger.getLogger(jFrameEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        mainMenu menu = new mainMenu();
        this.dispose();
        menu.setVisible(true);        

    }//GEN-LAST:event_btn_regresarActionPerformed

    private void txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyTyped
        // TODO add your handling code here:
        valN.valKeyTypeNumeros(evt);
        if (txt_telefono.getText().length() == 8) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_telefonoKeyTyped
    private void comboBoxPuesto(){
        cbb_puesto.removeAllItems();
        cbb_puesto.addItem("Seleccionar");
        
        List<decPuesto> mp = this.puestoDao.findclientesEntities();
        for (decPuesto unTipo : mp){
            if (unTipo.getDesactivado() == 0) {
                cbb_puesto.addItem(String.valueOf(unTipo.getNombre()));
            }
        }
    }
    private void comboBoxTipoDoc(){
        cbb_documento.removeAllItems();
        cbb_documento.addItem("Seleccionar");
        
        List<decTipoDeDocumento> tipoDocumento = tipoDocumentoDao.findclientesEntities();
        for (decTipoDeDocumento unTipo : tipoDocumento){
            if (unTipo.getDesactivado() == 0) {
                cbb_documento.addItem(String.valueOf(unTipo.getId_tipo_documento()));
            }
        }   
         
    }
    
    private void btn_desactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desactivarActionPerformed
        // TODO add your handling code here:
        if (!txt_id_area.getText().equals("")) {
            desactivar(parseInt(txt_id_area.getText()));
        } else {
            JOptionPane.showMessageDialog(this, "No selecciono ningún cliente a desactivar");
        }
    }//GEN-LAST:event_btn_desactivarActionPerformed

    private void tbl_registrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_registrosMouseClicked
        // TODO add your handling code here:
        int row = tbl_registros.getSelectedRow();
        TableModel model = tbl_registros.getModel();
        btn_agregar.setEnabled(false);
        btn_modificar.setEnabled(true);
        btn_desactivar.setEnabled(true);
        txt_id_area.setText(model.getValueAt(row, 0).toString());
        txt_nombre.setText(model.getValueAt(row, 1).toString());
        txt_apellido.setText(model.getValueAt(row, 2).toString());
        txt_telefono.setText(model.getValueAt(row, 3).toString());
        txt_direccion.setText(model.getValueAt(row, 4).toString());
        txt_email.setText(model.getValueAt(row, 5).toString());
        
        //txt_nombre_tipoDocumento.setText(model.getValueAt(row, 6).toString());
        //ID DE DOCUMENTO CUANDO ESTE LISTA LA TABLA
        cbb_puesto.setSelectedItem(model.getValueAt(row, 6).toString());
        cbb_documento.setSelectedItem(model.getValueAt(row, 7).toString());
        // TODO add your handling code here:
        txt_id_documento.setText(model.getValueAt(row, 9).toString());
    }//GEN-LAST:event_tbl_registrosMouseClicked

    private void txt_id_documentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_id_documentoKeyTyped
        // TODO add your handling code here:  
            if (txt_id_documento.getText().length() == 15) {
            evt.consume();} 
    }//GEN-LAST:event_txt_id_documentoKeyTyped

    private void cbb_documentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_documentoItemStateChanged
        // TODO add your handling code here:
        String input = cbb_documento.getSelectedItem().toString();
                //parseInt(cbb_mesas.getSelectedItem().toString()));
        
        try {
            parseInt(input);
            decTipoDeDocumento clienteBuscar = tipoDocumentoDao.findclientes(parseInt(input));
            if (clienteBuscar == null) {
                JOptionPane.showMessageDialog(this, "documento no encontrada");
            } else if (clienteBuscar.getDesactivado() == 1) {
                JOptionPane.showMessageDialog(this, "Documento actualmente desactivado");
            } else {
                
                String name = String.valueOf(clienteBuscar.getNombre());
                String fna = name;
                txt_nombre_tipoDocumento.setText(fna);
            }
        } catch (Exception ex) {
            Logger.getLogger(jFramePuesto.class
                .getName()).log(Level.SEVERE, null, ex);
            if (input.equals("Seleccionar")) {
                txt_nombre_tipoDocumento.setText("");
            }
        }
    }//GEN-LAST:event_cbb_documentoItemStateChanged

    private void cbb_puestoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_puestoItemStateChanged
           // TODO add your handling code here:
        String input = cbb_puesto.getSelectedItem().toString();
                //parseInt(cbb_mesas.getSelectedItem().toString()));
        
        try {
            parseInt(input);
            decPuesto clienteBuscar = puestoDao.findclientes(parseInt(input));
            if (clienteBuscar == null) {
                JOptionPane.showMessageDialog(this, "puesto no encontrada");
            } else if (clienteBuscar.getDesactivado() == 1) {
                JOptionPane.showMessageDialog(this, "puesto actualmente desactivado");
            } else {
                
                String name = String.valueOf(clienteBuscar.getNombre());
                String fna = name;
                
            }
        } catch (Exception ex) {
            Logger.getLogger(jFrameEmpleado.class
                .getName()).log(Level.SEVERE, null, ex);
            if (input.equals("Seleccionar")) {
                
            }
        }
    }//GEN-LAST:event_cbb_puestoItemStateChanged

    private void txt_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyTyped
        // TODO add your handling code here:
        valS.letras(evt);
        if(txt_nombre.getText().length() == 25){
            evt.consume();
        }
    }//GEN-LAST:event_txt_nombreKeyTyped

    private void txt_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidoKeyTyped
        // TODO add your handling code here:
        valS.letras(evt);
        if(txt_apellido.getText().length() == 25){
            evt.consume();
        }
    }//GEN-LAST:event_txt_apellidoKeyTyped

    private void txt_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_direccionKeyTyped
        // TODO add your handling code here:
        valS.letras(evt);
        if(txt_direccion.getText().length() == 25){
            evt.consume();
        }
    }//GEN-LAST:event_txt_direccionKeyTyped

    private void txt_telefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefonoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefonoKeyReleased

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        limpiar();
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void txt_emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyTyped
        // TODO add your handling code here:
        
        valS.consumeMayor25(evt, txt_email.getText());
    }//GEN-LAST:event_txt_emailKeyTyped
    private void limpiar() {
        txt_id_area.setText("");
        txt_nombre.setText("");
        txt_apellido.setText("");
        txt_telefono.setText("");
        txt_email.setText("");
        cbb_documento.setSelectedItem("Seleccionar");
        txt_id_documento.setText("");
        txt_direccion.setText("");
        txt_nombre_tipoDocumento.setText("");
        cbb_puesto.setSelectedItem("Seleccionar");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameEmpleado().setVisible(true);
            }
        });
        
    }
    private static int GetIdTipoDocumento(String Nombre)
    {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("base_datos_mysql");
        EntityManager em = emf.createEntityManager();
        String select = "select id_tipo_documento from decTipoDeDocumento where nombre = '"+ Nombre+ "'";
        Query query = em.createQuery(select);
    
        return Integer.parseInt(query.getSingleResult().toString());           
    }
    private static int GetIdPuesto(String Nombre)
    {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("base_datos_mysql");
        EntityManager em = emf.createEntityManager();
        String select = "select id_tipo_documento from decTipoDeDocumento where nombre = '"+ Nombre+ "'";
        Query query = em.createQuery(select);
    
        return Integer.parseInt(query.getSingleResult().toString());           
    }
    
    private void desactivar(int id) {
        empleado.setId_empleado(id);
        empleado.setNombre(txt_nombre.getText());
        empleado.setApellido(txt_apellido.getText());
        empleado.setTelefono(Integer.parseInt(txt_telefono.getText()));
        empleado.setEmail(txt_email.getText());
        empleado.setDireccion(txt_direccion.getText());
        empleado.setId_tipo_documento(GetIdTipoDocumento(String.valueOf(cbb_documento.getSelectedItem())));
        empleado.setDesactivado(1);
        try {
            empleadoDao.edit(empleado);
        } catch (Exception ex) {
            Logger.getLogger(jFrameEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_desactivar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JComboBox<String> cbb_documento;
    private javax.swing.JComboBox<String> cbb_puesto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_id_menu;
    private javax.swing.JLabel lbl_menu_restaurante;
    private javax.swing.JTable tbl_registros;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id_area;
    private javax.swing.JTextField txt_id_documento;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombre_tipoDocumento;
    private javax.swing.JTextField txt_telefono;
    // End of variables declaration//GEN-END:variables
}
