/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.vulkan.gui;
import com.mycompany.controlador.controlClientes;
import com.mycompany.controlador.controlEmpleado;
import com.mycompany.controlador.controlMenu;
import com.mycompany.controlador.controlMesas;
import com.mycompany.vulkan.validacion.valNumero;
import com.mycompany.vulkan.validacion.valString;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import static java.lang.Integer.parseInt;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import vulkan.declaracion.decClientes;
import vulkan.declaracion.decEmpleado;
import vulkan.declaracion.decMesas;
import com.mycompany.vulkan.validacion.fechaActual;
import java.util.ArrayList;
import vulkan.declaracion.decPedidos;
import com.mycompany.controlador.controlPedidos;

/**
 * @author fer3dev
 */

public class jFramePedidos extends javax.swing.JFrame {
    valString valS = new valString();
    valNumero valN = new valNumero();
    controlClientes clientesDao = new controlClientes();
    controlMesas mesasDao = new controlMesas();
    controlMenu menu = new controlMenu();
    controlEmpleado empleadoDao = new controlEmpleado();
    fechaActual fechactual = new fechaActual();
    controlPedidos pedidosDao = new controlPedidos();
    static DefaultTableModel t2;
    
    /**
     * Creates new form jFramePlantilla
     */
    public jFramePedidos() {
        initComponents();
        this.llenarTabla();
        this.comboBoxMesero();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void llenarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        tbl_registros.setModel(modelo);
        modelo.addColumn("Id pedido");
        modelo.addColumn("id_cliente");
        modelo.addColumn("getId_empleado_mesero");
        modelo.addColumn("fecha inicio");
        modelo.addColumn("Pedido en linea");
        modelo.addColumn("Pedidos");
        modelo.addColumn("Cantidad");
        List<decPedidos> puesto = pedidosDao.findMesasEntities();

        for(decPedidos cliente : puesto){
            modelo.addRow(
                new Object[]{
                    cliente.getId_pedido(),
                    cliente.getId_cliente(),
                    cliente.getId_empleado_mesero(),
                    cliente.getFecha_inicio(),
                    
                    cliente.getPedido_en_linea(),
                    cliente.getId_menu(),
                    
                }
            );
        }
        btn_modificar.setEnabled(false);
        btn_desactivar.setEnabled(false);
        btn_agregar.setEnabled(true);
        txt_fecha.setText(fechactual.getFechaActual());
        this.comboBoxMesero();
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lbl_puestos_trabajo = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btn_buscar_cliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_telefono_cliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_fecha = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        cbb_mesas = new javax.swing.JComboBox<>();
        txt_descripcion_mesa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbb_mesero = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        txt_busquedaMenu = new javax.swing.JTextField();
        btn_buscar_cliente1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_nombre1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_registros = new javax.swing.JTable();
        btn_update = new javax.swing.JButton();
        btn_agregar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_desactivar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(244, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1280, 300));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setPreferredSize(new java.awt.Dimension(1280, 50));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_puestos_trabajo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbl_puestos_trabajo.setText("Pedidos");
        jPanel4.add(lbl_puestos_trabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, -1, -1));

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_buscar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar20.png"))); // NOI18N
        btn_buscar_cliente.setPreferredSize(new java.awt.Dimension(20, 20));
        btn_buscar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_clienteActionPerformed(evt);
            }
        });
        jPanel6.add(btn_buscar_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, -1, -1));

        jLabel3.setText("ID");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, -1));

        txt_telefono_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_telefono_clienteKeyTyped(evt);
            }
        });
        jPanel6.add(txt_telefono_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 100, -1));

        jLabel5.setText("ID de cliente");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel10.setText("Nombre");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txt_nombre.setEditable(false);
        txt_nombre.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 220, -1));

        jLabel6.setText("Fecha");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txt_fecha.setEditable(false);
        txt_fecha.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 220, -1));

        jLabel7.setText("Nombre Mesero");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, -1, -1));

        jCheckBox1.setText("Pedido en linea");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel6.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, -1));

        cbb_mesas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_mesasItemStateChanged(evt);
            }
        });
        jPanel6.add(cbb_mesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 150, -1));

        txt_descripcion_mesa.setEditable(false);
        txt_descripcion_mesa.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.add(txt_descripcion_mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 220, 30));

        jLabel9.setText("ID mesa");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        cbb_mesero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(cbb_mesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, -1, -1));

        jToggleButton1.setText("Abir el menu");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, -1, -1));

        txt_busquedaMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_busquedaMenuKeyTyped(evt);
            }
        });
        jPanel6.add(txt_busquedaMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 100, -1));

        btn_buscar_cliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar20.png"))); // NOI18N
        btn_buscar_cliente1.setPreferredSize(new java.awt.Dimension(20, 20));
        btn_buscar_cliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_cliente1ActionPerformed(evt);
            }
        });
        jPanel6.add(btn_buscar_cliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, -1, -1));

        jLabel8.setText("Nombre del menu");
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, -1));

        txt_nombre1.setEditable(false);
        txt_nombre1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.add(txt_nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 220, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1110, 270));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo2.png"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BackgroundRes.png"))); // NOI18N
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

        tbl_registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_registros.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_registros.setSelectionBackground(new java.awt.Color(0, 255, 204));
        tbl_registros.setSelectionForeground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(tbl_registros);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1280, 310));

        btn_update.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar1.png"))); // NOI18N
        btn_update.setToolTipText("");
        btn_update.setPreferredSize(new java.awt.Dimension(50, 50));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        btn_agregar.setBackground(new java.awt.Color(204, 204, 204));
        btn_agregar.setForeground(new java.awt.Color(0, 0, 255));
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Añadir1.png"))); // NOI18N
        btn_agregar.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel2.add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, -1));

        btn_modificar.setBackground(new java.awt.Color(204, 204, 204));
        btn_modificar.setForeground(new java.awt.Color(0, 0, 255));
        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Modificar1.png"))); // NOI18N
        btn_modificar.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel2.add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, -1, -1));

        btn_desactivar.setBackground(new java.awt.Color(204, 204, 204));
        btn_desactivar.setForeground(new java.awt.Color(0, 0, 255));
        btn_desactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Desactivar1.png"))); // NOI18N
        btn_desactivar.setPreferredSize(new java.awt.Dimension(150, 50));
        jPanel2.add(btn_desactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, -1, -1));

        btn_regresar.setBackground(new java.awt.Color(204, 204, 204));
        btn_regresar.setForeground(new java.awt.Color(255, 0, 51));
        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar1.png"))); // NOI18N
        btn_regresar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        btn_regresar.setPreferredSize(new java.awt.Dimension(150, 50));
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BackgroundRes.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -250, -1, -1));

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        mainMenu menu = new mainMenu();
        this.dispose();
        menu.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_buscar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_clienteActionPerformed
        int a = GetIdCliente(txt_telefono_cliente.getText());
        String input = txt_telefono_cliente.getText();
        try {
            parseInt(input);
            decClientes clienteBuscar = clientesDao.findClientes(a);
            if (clienteBuscar == null) {
                JOptionPane.showMessageDialog(this, "Cliente no encontrada");
            } else if (clienteBuscar.getDesactivado() == 1) {
                JOptionPane.showMessageDialog(this, "Cliente actualmente desactivado");
            } else {
                String apll = String.valueOf(clienteBuscar.getApellido());
                String name = String.valueOf(clienteBuscar.getNombre());
                String fna = name + " " + apll;
                txt_nombre.setText(fna);
            }
        } catch (Exception ex) {
            Logger.getLogger(jFramePuesto.class
                .getName()).log(Level.SEVERE, null, ex);
            if (input != null) {
                JOptionPane.showMessageDialog(this, "El ID solo puede contener números");
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_buscar_clienteActionPerformed

    private void txt_telefono_clienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefono_clienteKeyTyped
        
        valN.valKeyTypeNumeros(evt);
        if (txt_telefono_cliente.getText().length() == 8) {
            evt.consume();
        }
        
    }//GEN-LAST:event_txt_telefono_clienteKeyTyped

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void cbb_mesasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_mesasItemStateChanged
        // TODO add your handling code here:
        String input = cbb_mesas.getSelectedItem().toString();
        //parseInt(cbb_mesas.getSelectedItem().toString()));

        try {
            parseInt(input);
            decMesas clienteBuscar = mesasDao.findMesas(parseInt(input));
            if (clienteBuscar == null) {
                JOptionPane.showMessageDialog(this, "documento no encontrada");
            } else if (clienteBuscar.getDesactivado() == 1) {
                JOptionPane.showMessageDialog(this, "Documento actualmente desactivado");
            } else {

                String name = String.valueOf(clienteBuscar.getDescripcion());
                String fna = name;
                txt_descripcion_mesa.setText(fna);
            }
        } catch (Exception ex) {
            Logger.getLogger(jFramePuesto.class
                .getName()).log(Level.SEVERE, null, ex);
            if (input.equals("Seleccionar")) {
                txt_descripcion_mesa.setText("");
            }
        }
    }//GEN-LAST:event_cbb_mesasItemStateChanged

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        llenarTabla();
    }//GEN-LAST:event_btn_updateActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        jFramebuscarMenu xz = new jFramebuscarMenu();
        xz.setVisible(true);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void txt_busquedaMenuKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busquedaMenuKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_busquedaMenuKeyTyped

    private void btn_buscar_cliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_cliente1ActionPerformed
        // TODO add your handling code here:
        int a = GetIdCliente(txt_telefono_cliente.getText());
        String input = txt_telefono_cliente.getText();
        try {
            parseInt(input);
            decClientes clienteBuscar = clientesDao.findClientes(a);
            if (clienteBuscar == null) {
                JOptionPane.showMessageDialog(this, "Cliente no encontrada");
            } else if (clienteBuscar.getDesactivado() == 1) {
                JOptionPane.showMessageDialog(this, "Cliente actualmente desactivado");
            } else {
                String apll = String.valueOf(clienteBuscar.getApellido());
                String name = String.valueOf(clienteBuscar.getNombre());
                String fna = name + " " + apll;
                txt_nombre.setText(fna);
            }
        } catch (Exception ex) {
            Logger.getLogger(jFramePuesto.class
                .getName()).log(Level.SEVERE, null, ex);
            if (input != null) {
                JOptionPane.showMessageDialog(this, "El ID solo puede contener números");
            }
        }
    }//GEN-LAST:event_btn_buscar_cliente1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFramePedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFramePedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFramePedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFramePedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFramePedidos().setVisible(true);
            }
        });
    }
    //Para buscar por telefono 
    private static int GetIdCliente(String Nombre)
    {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("base_datos_mysql");
        EntityManager em = emf.createEntityManager();
        String select = "select id_cliente from decClientes where telefono = "+ Nombre;
        Query query = em.createQuery(select);
    
        return Integer.parseInt(query.getSingleResult().toString());           
    }
    private static String GetsoloMesero()
    {
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("base_datos_mysql");
        EntityManager em = emf.createEntityManager();
        String select = "select nombre from decEmpleado where empleadoNombre_puesto = 'Mesero'";
        Query query = em.createQuery(select);
    
        return String.valueOf(query.getSingleResult().toString());           
    }
    private void comboBoxMesero(){
        //EntityManagerFactory emf = Persistence.createEntityManagerFactory("base_datos_mysql");
        //EntityManager em = emf.createEntityManager();
        //String select = "select nombre from decEmpleado where empleadoNombre_puesto = 'Mesero'";
        //Query query = em.createQuery(select);
        //String x = query.getSingleResult().toString().;
        //query.getParameters().toArray();
        //char[] ma = query.getSingleResult().toString().toCharArray();
        //List<String> xd = query.getSingleResult().toString();
        
        
        cbb_mesero.removeAllItems();
        cbb_mesero.addItem("Seleccionar");
        
        List<decEmpleado> mp = this.empleadoDao.findclientesEntities();
        for (decEmpleado unTipo : mp){
            if (unTipo.getDesactivado() == 0) {
                if (unTipo.getEmpleadoNombre_puesto().equals("Mesero")) {
                    cbb_mesero.addItem(String.valueOf(unTipo.getNombre()));
            }}
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar_cliente;
    private javax.swing.JButton btn_buscar_cliente1;
    private javax.swing.JButton btn_desactivar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cbb_mesas;
    private javax.swing.JComboBox<String> cbb_mesero;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lbl_puestos_trabajo;
    private javax.swing.JTable tbl_registros;
    private javax.swing.JTextField txt_busquedaMenu;
    private javax.swing.JTextField txt_descripcion_mesa;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombre1;
    private javax.swing.JTextField txt_telefono_cliente;
    // End of variables declaration//GEN-END:variables
}
