/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vulkan.gui;

import com.mycompany.vulkan.gui.jFrameMenu;
/**
 *
 * @author gabri
 */
public class mainMenu extends javax.swing.JFrame {
    //jFramePuesto framePuesto = new jFramePuesto();
    jFrameMenu frameMenu = new jFrameMenu();
    
    /**
     * Creates new form mainMenu
     */
    public mainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btn_clientes = new javax.swing.JButton();
        btn_empleados = new javax.swing.JButton();
        btn_proveedores = new javax.swing.JButton();
        btn_inventario = new javax.swing.JButton();
        btn_factura = new javax.swing.JButton();
        btn_pedidos = new javax.swing.JButton();
        btn_mesas = new javax.swing.JButton();
        btn_reservaciones = new javax.swing.JButton();
        btn_historial_precios = new javax.swing.JButton();
        btn_tipo_documento = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();
        btn_cerrar_sesion = new javax.swing.JButton();
        btn_Puesto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        titulo.setLayout(new java.awt.GridBagLayout());

        lbl_titulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(0, 0, 255));
        lbl_titulo.setText("MENU PRINCIPAL");
        titulo.add(lbl_titulo, new java.awt.GridBagConstraints());

        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 80));

        menu.setBackground(new java.awt.Color(244, 255, 255));
        menu.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(new java.awt.Color(244, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1100, 400));
        jPanel4.setLayout(new java.awt.GridLayout(2, 7, 20, 100));

        btn_clientes.setBackground(new java.awt.Color(204, 204, 204));
        btn_clientes.setForeground(new java.awt.Color(0, 0, 255));
        btn_clientes.setText("Clientes");
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });
        jPanel4.add(btn_clientes);

        btn_empleados.setBackground(new java.awt.Color(204, 204, 204));
        btn_empleados.setForeground(new java.awt.Color(0, 0, 255));
        btn_empleados.setText("Empleados");
        jPanel4.add(btn_empleados);

        btn_proveedores.setBackground(new java.awt.Color(204, 204, 204));
        btn_proveedores.setForeground(new java.awt.Color(0, 0, 255));
        btn_proveedores.setText("Proveedores");
        jPanel4.add(btn_proveedores);

        btn_inventario.setBackground(new java.awt.Color(204, 204, 204));
        btn_inventario.setForeground(new java.awt.Color(0, 0, 255));
        btn_inventario.setText("Inventario");
        jPanel4.add(btn_inventario);

        btn_factura.setBackground(new java.awt.Color(204, 204, 204));
        btn_factura.setForeground(new java.awt.Color(0, 0, 255));
        btn_factura.setText("Factura");
        jPanel4.add(btn_factura);

        btn_pedidos.setBackground(new java.awt.Color(204, 204, 204));
        btn_pedidos.setForeground(new java.awt.Color(0, 0, 255));
        btn_pedidos.setText("Pedidos");
        jPanel4.add(btn_pedidos);

        btn_mesas.setBackground(new java.awt.Color(204, 204, 204));
        btn_mesas.setForeground(new java.awt.Color(0, 0, 255));
        btn_mesas.setText("Mesas");
        btn_mesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mesasActionPerformed(evt);
            }
        });
        jPanel4.add(btn_mesas);

        btn_reservaciones.setBackground(new java.awt.Color(204, 204, 204));
        btn_reservaciones.setForeground(new java.awt.Color(0, 0, 255));
        btn_reservaciones.setText("Reservaciones");
        jPanel4.add(btn_reservaciones);

        btn_historial_precios.setBackground(new java.awt.Color(204, 204, 204));
        btn_historial_precios.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_historial_precios.setForeground(new java.awt.Color(0, 0, 255));
        btn_historial_precios.setText("Historial de precios");
        jPanel4.add(btn_historial_precios);

        btn_tipo_documento.setBackground(new java.awt.Color(204, 204, 204));
        btn_tipo_documento.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        btn_tipo_documento.setForeground(new java.awt.Color(0, 0, 255));
        btn_tipo_documento.setText("Tipos de Documento");
        btn_tipo_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tipo_documentoActionPerformed(evt);
            }
        });
        jPanel4.add(btn_tipo_documento);

        btn_menu.setBackground(new java.awt.Color(204, 204, 204));
        btn_menu.setForeground(new java.awt.Color(0, 0, 255));
        btn_menu.setText("Menu");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        jPanel4.add(btn_menu);

        btn_cerrar_sesion.setBackground(new java.awt.Color(204, 204, 204));
        btn_cerrar_sesion.setForeground(new java.awt.Color(255, 0, 51));
        btn_cerrar_sesion.setText("Cerrar Sesion");
        jPanel4.add(btn_cerrar_sesion);

        menu.add(jPanel4, new java.awt.GridBagConstraints());

        btn_Puesto.setBackground(new java.awt.Color(204, 204, 204));
        btn_Puesto.setForeground(new java.awt.Color(0, 0, 255));
        btn_Puesto.setText("Tipo Puesto");
        btn_Puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PuestoActionPerformed(evt);
            }
        });
        menu.add(btn_Puesto, new java.awt.GridBagConstraints());

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1310, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clientesActionPerformed

    private void btn_mesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mesasActionPerformed

    private void btn_tipo_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tipo_documentoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btn_tipo_documentoActionPerformed

    private void btn_PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PuestoActionPerformed
        // TODO add your handling code here:
        //framePuesto.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_btn_PuestoActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        frameMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Puesto;
    private javax.swing.JButton btn_cerrar_sesion;
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_empleados;
    private javax.swing.JButton btn_factura;
    private javax.swing.JButton btn_historial_precios;
    private javax.swing.JButton btn_inventario;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_mesas;
    private javax.swing.JButton btn_pedidos;
    private javax.swing.JButton btn_proveedores;
    private javax.swing.JButton btn_reservaciones;
    private javax.swing.JButton btn_tipo_documento;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel titulo;
    // End of variables declaration//GEN-END:variables
}
